### ISSUE TITLE
Various issues encountered so far

### ISSUE THREAD

**Issue by sthegreat** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#6]
Version: TFR 3.3.1.3-international

I've been playing TFR, and kept track of any issues I noticed while playing up to the late bronze age, where I am now. Here they are in list format.

Questing:

-What you remember does not apply here #370 -- Doesn't work with vanilla/GT sticks, not a huge issue but I couldn't figure it out at the time.

-Pottery #2 -- Fired molds count as complete before firing

-Food quests count as complete even without a full stack, such as the farming quests. Maybe intended maybe not idk

-Quests do not autocomplete and there is some lag after completing a quest before rewards can be claimed.

Localization:

-Many quests lack localized descriptions

-Ammonium Chloride dust has no localized name

-Automatedbellowsaddon mod has Chinese item names; English ones should exist as the original mod was English, no?

Gameplay:

-My default keybinds for nei were all messed up to start (other keys instead of R, U, etc.) and those ones are out of the way to change so I'd suggest trying to keep them at defaults so players are not confused

-Acacia leaves immediately decay after worldgen, leading to skeleton forests and leading to frame drops when walking through newly generated acacia forests.

-Vanilla and TFC sticks both generate on the ground which may be difficult to fix, however, vanilla sticks are also renamed "Stick (TFC)" which they should not be, making things even more confusing.

-Mobs don't seem to spawn in spawnchunks at all, possibly a config in something like FTBU?

-Modtweaker sometimes complains about bad scripts on world load, idk if it's an issue

-Hevea trees grow wrong, all same short height and very few leaves so you get less than 1 sapling, and the logs they drop are buggy and don't go into log piles properly

-Rich/Normal ores must be crushed in the rock crusher before the GT crusher, but poor ores can be put in the GT crusher immediately and sometimes give different drops -- these recipes may be autogenerated because of the orePoor tag?

-Reeds processing with base potash liquor in barrel doesn't work at all for me, no output when the barrel is sealed, this makes the earlygame paper quest impossible until you can do it in the bath.

-Nei gets "stuck" sometimes and won't update when you type, this requires a pack relaunch to fix. This seems to be triggered by searching for a mod the pack doesn't have using @, e.g. typing @buildcraft

-A quest or a book given to the player should describe the new locations of ores. Currently they would have to check the config to see, for example, that they don't need Gabbro to find garnierite.

-The "items popping to your hotbar" feature is buggy and unreliable; I'm not sure which mod adds this but I'd consider disabling it.

-Colored backpacks are cheaper than the brown ones, also medium backpacks have no textures

Balance:

-Cassiterite is way way too common, I know you want the player to be able to easily get normal bronze for GT machines later but like 1/3 of the veins I see are cassiterite. The rates could be dropped quite a lot and I'd still have plenty for GT. Probably don't drop them all the way back to the default rate though.

-The new TFC glass process seems fairly useless because I can still just cook sand, if you want people to use the new one you should probably disable that.

-The bed can be made from jute via jute->string, is this intended? Normally you must get wool or spider string. It's not a big issue  either way.

-Udary mod sulfuric/nitric acid should be different fluids from GT sulfuric/nitric acids. Udary has much simpler recipes for those acids, which can now be used in GT machines.

-Coins are pretty overpowered. You can obtain plenty of coins by turning in dyes and lumber and stuff, and then you can get a ton of valuable ingots, for example 20 nickel!, or like 56 copper or 40 bronze, for just 10 coins. The nickel in particular makes the Udary mod ore processing useless (it has you processing a ton of limonite to get just a small amount of nickel, for if you can't find a nickel vein. It similarly allows small amounts of silver from galena), and in general the coins let a player progress much faster than they normally would as they can find/mine/process less ore. I would suggest reducing the amount of ingots you get by a lot (maybe to like 1-8 depending on the metal?) and making it so you cannot get something from coins before you do a quest requiring you to have gotten at least a little bit of it by yourself.

-By alloying in TFC and then separating in GT you can transmute metals in weird ways, copper -> tin is one simple example but there are plenty of rarer metals that can be generated in this way. There should be no GT centrifuge recipes to separate TFC alloys to prevent this.

-Extra bees metal bees allow you to skip normal GT gating for certain metals such as titanium and tungsten, and bees are not hard to obtain with gendustry cheaply available. I would suggest that you have it require a metal block to breed the bees, and/or requiring more technology to process the combs so nothing can be skipped in this way. However, note that the player can skip a breeding requirement using the mutatron or advanced mutatron so those must get more lategame recipes if you intend to gate via metal block breeding requirements.

edit: another one -- My newly crafted bronze GT wrench doesn't seem to count for the quest "wrench" #108

**Comment by yuesha-yc** [comment]
-My default keybinds for nei were all messed up to start (other keys instead of R, U, etc.) and those ones are out of the way to change so I'd suggest trying to keep them at defaults so players are not confused
I didn't actually changed the keybinds ^^

-Acacia leaves immediately decay after worldgen, leading to skeleton forests and leading to frame drops when walking through newly generated acacia forests.
This seems to be a server-only bug. Did you play on server or single?

-Vanilla and TFC sticks both generate on the ground which may be difficult to fix, however, vanilla sticks are also renamed "Stick (TFC)" which they should not be, making things even more confusing.
Fixed

-Mobs don't seem to spawn in spawnchunks at all, possibly a config in something like FTBU?
Not sure what you mean

-Modtweaker sometimes complains about bad scripts on world load, idk if it's an issue
NVM that warning. it wont affect anything

-Hevea trees grow wrong, all same short height and very few leaves so you get less than 1 sapling, and the logs they drop are buggy and don't go into log piles properly

-Rich/Normal ores must be crushed in the rock crusher before the GT crusher, but poor ores can be put in the GT crusher immediately and sometimes give different drops -- these recipes may be autogenerated because of the orePoor tag?
Well it is intended to let you crush bigger ores in the rock crusher. For the poor ores being able to crush? You won't get as many crushed ore in this way, compared to rock-crushing into small ores first.

-Reeds processing with base potash liquor in barrel doesn't work at all for me, no output when the barrel is sealed, this makes the earlygame paper quest impossible until you can do it in the bath.
Fixed

-Nei gets "stuck" sometimes and won't update when you type, this requires a pack relaunch to fix. This seems to be triggered by searching for a mod the pack doesn't have using @, e.g. typing @BuildCraft
NEI bug. I don't have an idea how to fix it sorry. 

-A quest or a book given to the player should describe the new locations of ores. Currently they would have to check the config to see, for example, that they don't need Gabbro to find garnierite.
Good suggestion. I will create a wiki page for this and put the link in the quest book. 

-The "items popping to your hotbar" feature is buggy and unreliable; I'm not sure which mod adds this but I'd consider disabling it.
Fixed

-Colored backpacks are cheaper than the brown ones, also medium backpacks have no textures
The backpack mod author did not upload the newest version on CF.

**Comment by sthegreat** [comment]
>-Acacia leaves immediately decay after worldgen, leading to skeleton forests and leading to frame drops when walking through newly generated acacia forests.
>This seems to be a server-only bug. Did you play on server or single?

Single player.

>-Mobs don't seem to spawn in spawnchunks at all, possibly a config in something like FTBU?
>Not sure what you mean

Hostile mobs do not spawn at night for me when close to the world spawn point. They spawn fine in other locations. I don't *think* it's the terrafirmacraft reducing spawns in chunks you spend time in mechanic, because I noticed this right at the first night when I started playing.

>-Rich/Normal ores must be crushed in the rock crusher before the GT crusher, but poor ores can be put in the GT crusher immediately and sometimes give different drops -- these recipes may be autogenerated because of the orePoor tag?
>Well it is intended to let you crush bigger ores in the rock crusher to get smaller ores in order to crush them in the GT crusher

what I'm referring to is these recipes using poor 15 unit ores:
![](https://i.imgur.com/k47zLxc.png)
normally you would first crush that in the crusher for the native copper nuggets, then crush those and get crushed chalcopyrite ore instead of crushed copper

**Comment by yuesha-yc** [comment]
The acacia issues is fixed. Yes the mob is a TFC mechanic. OK but I think most people won't choose this recipe. I will delete it next time.

**Comment by yuesha-yc** [comment]
@sthegreat  Did you update to 3.3.4.0? Everything Okay now?

**Comment by yuesha-yc** [comment]
Everything in this issue should be fixed now
